In [45]:
import importlib
import API_CF
importlib.reload(API_CF)

from API_CF import API_CF

In [46]:
CF = API_CF()

In [36]:
problems = CF.get_problems()
problems

,contestId,index,name,type,points,tags,rating
0,2110,F,Faculty,PROGRAMMING,3000.0,"[brute force, math, number theory]",NaN
1,2110,E,Melody,PROGRAMMING,2250.0,"[dfs and similar, graphs, implementation]",NaN
2,2110,D,Fewer Batteries,PROGRAMMING,2000.0,"[binary search, dfs and similar, dp, graphs, g...",NaN
3,2110,C,Racing,PROGRAMMING,1500.0,"[constructive algorithms, greedy]",NaN
4,2110,B,Down with Brackets,PROGRAMMING,750.0,[strings],NaN
...,...,...,...,...,...,...,...
10423,2,B,The least round way,PROGRAMMING,NaN,"[dp, math]",2000.0
10424,2,A,Winner,PROGRAMMING,NaN,"[hashing, implementation]",1500.0
10425,1,C,Ancient Berland Circus,PROGRAMMING,NaN,"[geometry, math]",2100.0
10426,1,B,Spreadsheet,PROGRAMMING,NaN,"[implementation, math]",1600.0
10427,1,A,Theatre Square,PROGRAMMING,NaN,[math],1000.0

In [38]:
st = CF.get_stats()
st

       contestId index  solvedCount
0           2110     F          612
1           2110     E          890
2           2110     D         3948
3           2110     C         8979
4           2110     B        16225
...          ...   ...          ...
10423          2     B        11549
10424          2     A        28360
10425          1     C         5931
10426          1     B        24024
10427          1     A       284403

[10428 rows x 3 columns]

In [48]:
problems = CF.get_problems()

In [49]:
problems

,contestId,index,name,type,points,tags,rating,solvedCount
0,2110,F,Faculty,PROGRAMMING,3000.0,"[brute force, math, number theory]",NaN,612
1,2110,E,Melody,PROGRAMMING,2250.0,"[dfs and similar, graphs, implementation]",NaN,890
2,2110,D,Fewer Batteries,PROGRAMMING,2000.0,"[binary search, dfs and similar, dp, graphs, g...",NaN,3954
3,2110,C,Racing,PROGRAMMING,1500.0,"[constructive algorithms, greedy]",NaN,8984
4,2110,B,Down with Brackets,PROGRAMMING,750.0,[strings],NaN,16232
...,...,...,...,...,...,...,...,...
10423,2,B,The least round way,PROGRAMMING,NaN,"[dp, math]",2000.0,11549
10424,2,A,Winner,PROGRAMMING,NaN,"[hashing, implementation]",1500.0,28360
10425,1,C,Ancient Berland Circus,PROGRAMMING,NaN,"[geometry, math]",2100.0,5931
10426,1,B,Spreadsheet,PROGRAMMING,NaN,"[implementation, math]",1600.0,24024
10427,1,A,Theatre Square,PROGRAMMING,NaN,[math],1000.0,284404

In [13]:
sub = CF.get_user_submissions("kuramu")

In [14]:
sub

,problem_id,name,contestId,index,attempts,solved,time_to_solve_seconds,relative_time_in_contest,struggle_percent,verdict,language,timeConsumedMillis,memoryConsumedBytes
0,1028A,Find Square,1028,A,1,False,NaN,NaN,100.0,COMPILATION_ERROR,C++20 (GCC 13-64),NaN,NaN
1,102951A,Maximum Distance,102951,A,2,True,0.0,2.147484e+09,20.0,OK,C++17 (GCC 7-32),249.0,102400.0
2,102961H,Maximum Subarray Sum,102961,H,1,True,0.0,2.147484e+09,10.0,OK,C++20 (GCC 11-64),46.0,1638400.0
3,103274C,Cypher Decypher,103274,C,1,True,0.0,1.342000e+03,10.0,OK,C++17 (GCC 7-32),202.0,12288000.0
4,103274E,Escape Room,103274,E,7,False,NaN,NaN,100.0,WRONG_ANSWER,C++20 (GCC 13-64),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,59A,Word,59,A,1,True,0.0,2.147484e+09,10.0,OK,C++20 (GCC 11-64),30.0,0.0
495,616B,Dinner with Emma,616,B,1,True,0.0,2.147484e+09,10.0,OK,C++20 (GCC 13-64),62.0,0.0
496,755C,PolandBall and Forest,755,C,2,True,196.0,2.147484e+09,20.0,OK,C++20 (GCC 13-64),62.0,102400.0
497,802A,Heidi and Library (easy),802,A,1,False,NaN,NaN,100.0,WRONG_ANSWER,C++20 (GCC 13-64),NaN,NaN
498,802G,Fake News (easy),802,G,1,True,0.0,2.147484e+09,10.0,OK,C++20 (GCC 13-64),77.0,102400.0

In [36]:
CF.get_user_info("quicksouls")

{'handle': 'QuickSouls',
 'rating': 858,
 'maxRating': 935,
 'rank': 'newbie',
 'maxRank': 'newbie',
 'contribution': 0,
 'friendOfCount': 10}

In [39]:
CF.get_user_rating_history("quicksouls")

,contestId,contestName,handle,rank,ratingUpdateTimeSeconds,oldRating,newRating
0,1926,Codeforces Round 928 (Div. 4),QuickSouls,22975,1708361400,0,363
1,1941,Codeforces Round 933 (Div. 3),QuickSouls,22511,1710175800,363,595
2,1950,Codeforces Round 937 (Div. 4),QuickSouls,19383,1711645200,595,765
3,1955,Codeforces Round 938 (Div. 3),QuickSouls,16607,1712595000,765,856
4,1968,Codeforces Round 943 (Div. 3),QuickSouls,12775,1714669200,856,911
5,2050,Codeforces Round 991 (Div. 3),QuickSouls,12092,1733417400,911,935
6,2055,Codeforces Round 996 (Div. 2),QuickSouls,17018,1736699700,935,896
7,2060,Codeforces Round 998 (Div. 3),QuickSouls,20944,1737306300,896,837
8,2065,Codeforces Round 1003 (Div. 4),QuickSouls,23873,1739119800,837,780
9,2093,Codeforces Round 1016 (Div. 3),QuickSouls,11235,1744131000,780,858

In [44]:
CF.get_contest_list(True)

,id,name,type,phase,frozen,durationSeconds,description,difficulty,kind,season,startTimeSeconds,relativeTimeSeconds,preparedBy,country,city,icpcRegion,websiteUrl,freezeDurationSeconds
0,100001,2010 Codeforces Beta Round #1 (training),ICPC,FINISHED,False,7200,This is the only contest for testing Codeforce...,3.0,Training Contest,2010-2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100003,2008-2009 Всероссийская командная олимпиада шк...,ICPC,FINISHED,False,18000,NaN,3.0,Official School Contest,2008-2009,1.453514e+09,294691020.0,Edvard,Russia,Saint Petersburg,NaN,NaN,NaN
2,100002,2002-2003 ACM-ICPC Northeastern European Regio...,ICPC,FINISHED,False,18000,NaN,4.0,Official ICPC Contest,2002-2003,NaN,NaN,MikeMirzayanov,Russia,Saint Petersburg,Northeastern Europe Region,NaN,NaN
3,100005,2010-2011 Цикл интернет-олимпиад. Вторая коман...,ICPC,FINISHED,False,18000,NaN,3.0,Training Contest,2010-2011,NaN,NaN,PavelKunyavskiy,Russia,NaN,NaN,NaN,NaN
4,100004,Local Contest,ICPC,FINISHED,False,10800,NaN,3.0,Official School Contest,2017-2018,1.511928e+09,236277420.0,MikeMirzayanov,Uzbekistan,Namangan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264,105910,The 23rd Sichuan University Programming Contest,ICPC,FINISHED,False,18000,NaN,3.0,School/University/City/Region Championship,2025-2026,NaN,NaN,hungry123,China,NaN,NaN,NaN,NaN
2265,105920,Soy Cup #1: Firefly,ICPC,FINISHED,False,18000,NaN,3.0,Official International Personal Contest,NaN,1.739077e+09,9128221.0,-firefly-,NaN,NaN,NaN,NaN,NaN
2266,105922,The 18th Jilin Provincial Collegiate Programmi...,ICPC,FINISHED,False,18000,NaN,3.0,School/University/City/Region Championship,2025-2026,1.748048e+09,157021.0,w4p3r,China,Changchun,NaN,NaN,NaN
2267,105925,SBC Brazilian Phase Zero 2025,ICPC,FINISHED,False,18000,NaN,3.0,NaN,NaN,NaN,NaN,Ayalla,Brazil,NaN,NaN,NaN,NaN
2268,105924,The 2025 CCPC National Invitational Contest (N...,ICPC,FINISHED,False,18000,NaN,3.0,NaN,2025-2026,1.748136e+09,69121.0,ouqingliang,China,Changchun,NaN,NaN,NaN

In [47]:
CF.get_rated_list()

,lastName,country,lastOnlineTimeSeconds,city,rating,friendOfCount,titlePhoto,handle,avatar,firstName,contribution,organization,rank,maxRating,registrationTimeSeconds,maxRank,vkId,email,openId
0,Korotkevich,Belarus,1748123757,Gomel,3843,80695,https://userpic.codeforces.org/422/title/50a27...,tourist,https://userpic.codeforces.org/422/avatar/2b5d...,Gennady,0,ITMO University,legendary grandmaster,4009,1265987288,tourist,NaN,NaN,NaN
1,Jiang,China,1747673889,Chongqing,3700,38140,https://userpic.codeforces.org/887306/title/b4...,jiangly,https://userpic.codeforces.org/887306/avatar/c...,Lingyu,0,Jiangly Fan Club,legendary grandmaster,4039,1547985852,jiangly,NaN,NaN,NaN
2,Zhou,China,1748038266,Hangzhou,3696,6432,https://userpic.codeforces.org/no-title.jpg,orzdevinwang,https://userpic.codeforces.org/no-avatar.jpg,Kangyang,0,Explosive Vegetable Club,legendary grandmaster,3844,1583069392,legendary grandmaster,NaN,NaN,NaN
3,Radecki,Poland,1748069779,Warsaw,3631,12380,https://userpic.codeforces.org/147752/title/13...,Radewoosh,https://userpic.codeforces.org/147752/avatar/a...,Mateusz,0,University of Warsaw,legendary grandmaster,3759,1385208270,legendary grandmaster,NaN,NaN,NaN
4,Romashov,Russia,1748130311,Barnaul,3556,2145,https://userpic.codeforces.org/1250517/title/d...,Ormlis,https://userpic.codeforces.org/1250517/avatar/...,Fedor,0,Higher School of Economics,legendary grandmaster,3641,1568806149,legendary grandmaster,259250989,rom.fedor@bk.ru,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43770,NaN,Egypt,1748109945,Al Khānkah,2,41,https://userpic.codeforces.org/3062008/title/c...,MohmedGado_255,https://userpic.codeforces.org/3062008/avatar/...,NaN,0,Ahram Canadian University,newbie,1149,1675273432,newbie,NaN,NaN,NaN
43771,Tadokoro,Japan,1747042854,Tokyo,-29,24,https://userpic.codeforces.org/no-title.jpg,BouncyHunter,https://userpic.codeforces.org/no-avatar.jpg,Kouji,0,Negative Rating Club,newbie,732,1693531712,newbie,NaN,NaN,NaN
43772,NaN,Azerbaijan,1747406253,NaN,-32,87,https://userpic.codeforces.org/no-title.jpg,0pt1mus23,https://userpic.codeforces.org/no-avatar.jpg,NaN,0,IRC23,newbie,1665,1717926068,expert,NaN,NaN,NaN
43773,No 1,China,1748095270,Burang,-32,15,https://userpic.codeforces.org/no-title.jpg,callback,https://userpic.codeforces.org/no-avatar.jpg,Katil,0,Kung Fu Hustle,newbie,1627,1611663521,expert,NaN,NaN,NaN
43774,(hidden alt acc),Egypt,1746458340,NaN,-34,14,https://userpic.codeforces.org/2864835/title/f...,Anne_without_TLE,https://userpic.codeforces.org/2864835/avatar/...,Habiba Abdelhady,0,,newbie,1073,1666728767,newbie,NaN,NaN,NaN